services:
  datahub:
    build: datahub
    container_name: datahub
    restart: unless-stopped
  analyzer:
    build: analyzer
    container_name: analyzer
    restart: unless-stopped
  notifier:
    build: notifier
    container_name: notifier
    restart: unless-stopped
  drawer:
    build: drawer
    container_name: drawer
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "15672:15672"
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=a1an
      - RABBITMQ_DEFAULT_PASS=1314
  consul:
    image: hashicorp/consul:1.20
    container_name: consul
    restart: unless-stopped
    ports:
      - "8500:8500"
    volumes:
      - ./data/consul:/consul/data
    command:
      - agent
      - -server
      - -ui
      - -bootstrap-expect=1
      - -client=0.0.0.0